### PR TITLE
WIP: Create epub from the source markdown

### LINKED ISSUE #41: ebook version
How about building the .mds into a .mobi or .ebook also in addition to static html?

### PR DESCRIPTION
**Pull request by pstavirs**
Run `./mkepub.py` to generate `sfosc.epub`.

You need to have `pandoc` installed and the python modules listed in `requirements.txt`

I'm not a native python programmer, so the script may not be idiomatic, but it works.

NOTE: Produced epub output is not clean - it contains hugo templates for example.

Fixes #41

### CODE REVIEW

**Comment by Beanow** [comment]
@pstavirs thank you for helping with this issue :smile:
I'm going to tinker with this a little to see if I can describe those dependencies with docker.

**Comment by Beanow** [comment]
For reference, this was the output I got.

[sfosc-epub.zip](https://github.com/sfosc/sfosc/files/3280635/sfosc-epub.zip)

**Comment by nothingismagick** [comment]
iBooks shows e.g. this:

Screen Shot 2019-06-12 at 11 30 27

**Comment by nothingismagick** [comment]
2 page spread:
Screen Shot 2019-06-12 at 11 31 26

**Comment by pstavirs** [comment]
The ordering thing is strange. I get the correct ordering -
```
['content/_index.md',
 'content/principles/_index.md',
 'content/business-models/_index.md',
 'content/business-models/none.md',
 'content/business-models/free-software-island.md',
 'content/business-models/loose-open-core.md',
 'content/business-models/tight-open-core.md',
 'content/business-models/dual-licensing.md',
 'content/business-models/as-a-service.md',
 'content/business-models/donations.md',
 'content/business-models/support.md',
 'content/business-models/free-software-product.md',
 'content/sfosc-book/_index.md',
 'content/sfosc-book/introduction.md',
 'content/sfosc-book/motivations.md',
 'content/sfosc-book/conception.md',
 'content/sfosc-book/institutions.md',
 'content/sfosc-book/rawls_for_foss.md',
 'content/sfosc-book/governance.md',
 'content/sfosc-book/contribution_and_distribution.md',
 'content/sfosc-book/business-models.md',
 'content/sfosc-book/the_way_forward.md',
 'content/social-contracts/_index.md',
 'content/social-contracts/donation.md']
```

Can you apply the following patch and attach the output here so I can check what is going wrong?

```diff
diff --git a/mkepub.py b/mkepub.py
index e5bc825..15134c1 100644
--- a/mkepub.py
+++ b/mkepub.py
@@ -24,15 +24,18 @@ for (root, dirs, files) in os.walk('content'):
         weight = page['weight'] if 'weight' in page else 0
         flist.append((f, weight))

+    pprint.pprint(flist)
     flist.sort(key = lambda x: x[1])
     oflist = [ft[0] for ft in flist]
     if len(oflist) == 0:
         continue
+    pprint.pprint(oflist)

     index = bisect.bisect(md, oflist[0])
     for f in oflist:
         md.insert(index, f)
         index += 1
+    pprint.pprint(md)
 pprint.pprint(md)

 print('Generating epub...')
```

**Comment by Beanow** [comment]
@pstavirs I've pushed my docker variation to https://github.com/Beanow/sfosc/tree/epub

You can run it with `./scripts/epub/mkepub.sh` from the root of the repository.

<details><summary>Click for the output I got</summary>

```
Retreiving input filenames and ordering them...
[('content/principles/_index.md', 1),
 ('content/social-contracts/_index.md', 105),
 ('content/sfosc-book/_index.md', 100),
 ('content/business-models/_index.md', 15)]
['content/principles/_index.md',
 'content/business-models/_index.md',
 'content/sfosc-book/_index.md',
 'content/social-contracts/_index.md']
['content/_index.md',
 'content/principles/_index.md',
 'content/business-models/_index.md',
 'content/sfosc-book/_index.md',
 'content/social-contracts/_index.md']
[]
[]
['content/social-contracts/donation.md']
['content/_index.md',
 'content/principles/_index.md',
 'content/business-models/_index.md',
 'content/sfosc-book/_index.md',
 'content/social-contracts/_index.md',
 'content/social-contracts/donation.md']
[]
['content/sfosc-book/introduction.md',
 'content/sfosc-book/motivations.md',
 'content/sfosc-book/conception.md',
 'content/sfosc-book/institutions.md',
 'content/sfosc-book/rawls_for_foss.md',
 'content/sfosc-book/governance.md',
 'content/sfosc-book/contribution_and_distribution.md',
 'content/sfosc-book/business-models.md',
 'content/sfosc-book/the_way_forward.md']
['content/_index.md',
 'content/principles/_index.md',
 'content/business-models/_index.md',
 'content/sfosc-book/_index.md',
 'content/sfosc-book/introduction.md',
 'content/sfosc-book/motivations.md',
 'content/sfosc-book/conception.md',
 'content/sfosc-book/institutions.md',
 'content/sfosc-book/rawls_for_foss.md',
 'content/sfosc-book/governance.md',
 'content/sfosc-book/contribution_and_distribution.md',
 'content/sfosc-book/business-models.md',
 'content/sfosc-book/the_way_forward.md',
 'content/social-contracts/_index.md',
 'content/social-contracts/donation.md']
[]
['content/business-models/none.md',
 'content/business-models/free-software-island.md',
 'content/business-models/loose-open-core.md',
 'content/business-models/tight-open-core.md',
 'content/business-models/dual-licensing.md',
 'content/business-models/as-a-service.md',
 'content/business-models/donations.md',
 'content/business-models/support.md',
 'content/business-models/free-software-product.md']
['content/_index.md',
 'content/business-models/none.md',
 'content/business-models/free-software-island.md',
 'content/business-models/loose-open-core.md',
 'content/business-models/tight-open-core.md',
 'content/business-models/dual-licensing.md',
 'content/business-models/as-a-service.md',
 'content/business-models/donations.md',
 'content/business-models/support.md',
 'content/business-models/free-software-product.md',
 'content/principles/_index.md',
 'content/business-models/_index.md',
 'content/sfosc-book/_index.md',
 'content/sfosc-book/introduction.md',
 'content/sfosc-book/motivations.md',
 'content/sfosc-book/conception.md',
 'content/sfosc-book/institutions.md',
 'content/sfosc-book/rawls_for_foss.md',
 'content/sfosc-book/governance.md',
 'content/sfosc-book/contribution_and_distribution.md',
 'content/sfosc-book/business-models.md',
 'content/sfosc-book/the_way_forward.md',
 'content/social-contracts/_index.md',
 'content/social-contracts/donation.md']
Writing order to order.txt file...
['content/_index.md',
 'content/business-models/none.md',
 'content/business-models/free-software-island.md',
 'content/business-models/loose-open-core.md',
 'content/business-models/tight-open-core.md',
 'content/business-models/dual-licensing.md',
 'content/business-models/as-a-service.md',
 'content/business-models/donations.md',
 'content/business-models/support.md',
 'content/business-models/free-software-product.md',
 'content/principles/_index.md',
 'content/business-models/_index.md',
 'content/sfosc-book/_index.md',
 'content/sfosc-book/introduction.md',
 'content/sfosc-book/motivations.md',
 'content/sfosc-book/conception.md',
 'content/sfosc-book/institutions.md',
 'content/sfosc-book/rawls_for_foss.md',
 'content/sfosc-book/governance.md',
 'content/sfosc-book/contribution_and_distribution.md',
 'content/sfosc-book/business-models.md',
 'content/sfosc-book/the_way_forward.md',
 'content/social-contracts/_index.md',
 'content/social-contracts/donation.md']
```

</details>

**Comment by Beanow** [comment]
Closing this for now, new comments can be tracked in the issue #41 or a new PR.

**Pull request closed without merging**
