### PR TITLE
adding vsoch to membership file

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

hey maintainers! I'm an avid participant in open source software communities, and I'm interested in this effort and want to help if I can. The most straight forward thing seems to be (to start) adding my name to the MEMBERSHIP.md file. Understandably this just means getting a vote, and I'll also follow the repository to see how else I might contribute. Looking forward to it!

### CODE REVIEW

**Comment by vsoch** [comment]
My misunderstanding - I thought being an avid open source developer was the requirement for membership, but you are saying in order to be a part, I need to already be a part of / participate in the community? It's a bit confusing, but I'd be glad to look at the issues board to see if I can offer any insight.

**Comment by vsoch** [comment]
I definitely don't quality then, thanks anyway!

**Comment by nothingismagick** [comment]
I think the only thing that is missing is some contribution to (or creation of) some issues here in this repo - or other links to things you have written that relate to this project.

**Comment by vsoch** [comment]
For that scope of work, I started good labs -> https://good-labs.github.io/ and we are working on the [Greater Good Pledge](https://good-labs.github.io/greater-good-pledge/) and some other projects to encourage transparent communication.  I also think about these things a lot :) https://vsoch.github.io/2019/transparency/

**Comment by nothingismagick** [comment]
Your page here shows a prolific contribution to open source @vsoch :
https://vsoch.github.io/work/

**Comment by vsoch** [comment]
Haha, yes, it's quite a problem! Just kidding :P

**Comment by nothingismagick** [comment]
And @Beanow - I didn't see your name in the MEMBERSHIP.md file and couldn't find your PR to that end. Did I miss it?

**Comment by Beanow** [comment]
Sorry @vsoch I did not mean to offend :sweat_smile:

My understanding was indeed like @nothingismagick said, on this repo.
I wasn't familiar with your work and seeing all this, I agree that doesn't make sense. I'll join #64, let's clear that up.

**Comment by vsoch** [comment]
No offense here at all! I definitely am okay with the established rule, just want to make sure it's clearly communicated. I'm super tired after a long day today, but I'll take a look at the discussion tomorrow and give any feedback that I might have.

**Comment by Beanow** [comment]
I think it's safe to say there will be support for a more open rule too. Looking forward to sorting that out so your membership can be approved :]

**Comment by Beanow** [comment]
@vsoch with your OK, I'll be happy to accept.
Considering you would meet all discussed possible requirements, including `involves:`, I don't see a reason to hold off on your membership any longer.

**Comment by vsoch** [comment]
Sounds good to me! Thanks @Beanow :)

**Pull request merged**
