### PR TITLE
Update the Xen / XenServer case study

### PR DESCRIPTION
**Pull request by mswilson**
... to mention that Citrix released the XenServer code as open source
over time.  That said, I don't think that XenServer is a pure support
play, I think that it was always an open core play. Pure support plays
make me think of LinuxCare and SpikeSource.

### CODE REVIEW

**Comment by adamhjk** [comment]
I took part of that history from here: https://www.brianmadden.com/opinion/A-brief-history-of-Xen-and-XenSource - in particular, the very early period of Xen's life (2003-2005). I don't know any of the players, so I'm not sure if they intended to create open core software or not (I mean, it makes a lot of sense that they would intend to).  Perhaps we should link to that as well, along with the referenced time period?

**Comment by adamhjk** [comment]
Also interesting that you mention XCP-ng, which has gone full circle - support and pro serve is the business model, apparently.

**Comment by adamhjk** [comment]
And, of course, I went hunting for Xen because of Peter Levine's "why there will never be another Red Hat", which is the number one referenced article in misunderstanding Red Hat's business model. https://techcrunch.com/2014/02/13/please-dont-tell-me-you-want-to-be-the-next-red-hat/

**Comment by adamhjk** [comment]
Also confirmed by the XenSource wayback machine, at least in early 2005: https://web.archive.org/web/20050204124627/http://www.xensource.com:80/index.html

**Comment by adamhjk** [comment]
Merging, and adding links.

**Comment by mswilson** [comment]
I suppose the difference in my mind was that XenSource was set up to **develop** Xen, not just support it.

**Pull request merged**
