### PR TITLE
First draft of new theme is ready!

### LINKED ISSUE #109: Explore docsy as a template for the site
We currently have a "book" sort of format, which is challenging as it expects chapters, and thus grouping things into logical buckets. Not everything fits in a bucket! We'd like to explore other kinds of templates and options, so I'm going to take a stab at docsy. Please assign me to this issue.

### PR DESCRIPTION
**Pull request by vsoch**
This is a *beast* to migrate the entire site to a new theme with docsy. It's totally gorgeous!
I added some notes to development.md that you should take note of:

 - you'll need to install hugo with the "extended" tag to render scss

Otherwise, give it a spin! I really like it. And this will close #109 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Sounds good! I’m glad you like it, I really do.

**Comment by Beanow** [comment]
Most changes have a bit of rationale in the full commit message.
Though haven't explained `Adhere to the attribution line from LICENSE.md`

I noticed you switched to "The SFOSC Authors" for the copyright statement which is similar to what's suggested for the wizard https://github.com/sfosc/wizard/issues/2 however I feel like deviating from what's stated in the license deserves it's own PR.
<sub>Although strictly speaking the previous version didn't adhere to the license either, "Adam Jacob, and contributors" vs "Adam Jacob and the SFOSC Contributors".</sub>

**Comment by vsoch** [comment]
hey @Beanow you've been a bit more quiet than usual, do you need help? If the dependencies are too much, I made a jekyll version (that doesn't need any kind of deploy, aside from pushing to GitHub) https://vsoch.github.io/docsy-jekyll/

**Comment by Beanow** [comment]
Yeah everything ok, definitely backlogged though :sweat_smile:
Is the jekyll switch for the local search? @Dinosaur

In terms of relying on GitHub to do dependency management for a Jekyll build, I would still want to keep some options open for setting up a build pipeline, for example if we'd want to integrate the wizard or sourcecred data into the main site. And there's the matter of local previews.

**Comment by vsoch** [comment]
haha I liked that you pinged me as dinosaur :) present!

This PR here is for the hugo version - so the search they have implemented (Google Custom Search) is what is present. For the jekyll version that I linked, that has lunr search.

It's very easy to build a jekyll site (as easy if not easier than) with Hugo - the only difference is that Jekyll just magically builds on GitHub pages, so we save needing to do it. You could of course do the same bit with having a deployment pipeline, but it seems unnecessarily complicated.  I would suggest taking a modular approach - having the main site build statically, using GitHub pages, and then having the sourcecred page with the data build to a separate repo (that is served under the same domain).

**Comment by vsoch** [comment]
Local previews are easy too - I just do `bundle exec jekyll build`. It really just comes down to one static site generator vs another. Hugo (in my small experience) seems to have a lot more dependency on all this npm / sass business, and is more complicated / error prone.

**Comment by vsoch** [comment]
It's totally up to you - I'm good with leaving the Hugo version here (and someone will need to work on fixing the search).

**Comment by Beanow** [comment]
> haha I liked that you pinged me as dinosaur :) present!

Heh! Discord copy paste.

Looking at the `bundle` command. That seems like a ruby dependency instead of node. So I don't think it's much different. However at least jekyll itself is part of the Gemfile, which I think is a plus.

The structure of the content seems to share the root folder with components used for the theme. This may be a little tricky to apply the two different licenses to.

**Comment by vsoch** [comment]
> The structure of the content seems to share the root folder with components used for the theme. This may be a little tricky to apply the two different licenses to.

Can you explain that?

**Comment by Beanow** [comment]
> > The structure of the content seems to share the root folder with components used for the theme. This may be a little tricky to apply the two different licenses to.
> 
> Can you explain that?

For example [_includes](https://github.com/vsoch/docsy-jekyll/tree/master/_includes) and [assets](https://github.com/vsoch/docsy-jekyll/tree/master/assets) as well as a the files in the root are theme and jekyll config related. They would be Apache 2 (from MIT) licensed. While [_docs](https://github.com/vsoch/docsy-jekyll/tree/master/_docs) and [_posts](https://github.com/vsoch/docsy-jekyll/tree/master/_posts) for example are content which would be CC BY-SA 4.0 licensed.

The folder structure has a less clear cut correspondence to which license applies to it. Perhaps this is solvable with a jekyll configuration change?

**Comment by vsoch** [comment]
Jekyll has a standard of having posts in `_posts`, and collections under folders like `_docs`. You could try putting them both in a subfolder (content) and changing the config, but I've never tried this.

**Comment by Beanow** [comment]
So, looking into this a little bit. So far I can think of a few routes.

The docker image `klakegg/hugo` seems to have PostCSS support and hugo extended but is missing the Git dependency. That means currently it won't build, but may offer a well-crafted image to build with when this is resolved. I've reported an issue here: https://github.com/klakegg/docker-hugo/issues/8 

We can switch to using a node + git image for builds and download or commit the hugo_extended binary to have the required dependencies. The downside is having a file download as a build dependency. We might work around this by copying the binary from a docker image instead, so it can at least be cached properly.

There's a hack to remove the PostCSS dependency (and node with that) by including a `node_modules/.bin/postcss` symlinked to a `node_modules/postcss-cli/bin/postcss` binary. With a no-op like:
```bash
#!/usr/bin/env bash
cat /dev/stdin
```
I've confirmed this will build and "skip" the PostCSS step. Otherwise, removing the PostCSS dependency would mean forking Docsy. Note: PostCSS is used for CSS vendor prefixes only. It will add a broader range of support for older browsers.

Jekyll I would need to do more research on, but it seems like builds would have cleaner dependency structures. I'm assuming the bulk of work would be in configuring and porting the content. As well as the licensing comment from before.

**Comment by vsoch** [comment]
This is correct. Let me know what you decide to do!

**Comment by Beanow** [comment]
The git dependency was added (already! :tada:) in https://github.com/klakegg/docker-hugo/issues/8 And it seems to work great now.

It does mean we need to upgrade to hugo 0.56.x as it's not applied to earlier versions. But looking into https://github.com/gohugoio/hugo/releases I haven't found a reason why we shouldn't. It's considered a major release because an undocumented feature was removed. And we're already upgrading from non-extended to extended + postcss + git, so the environment will require upgrades anyway.

Although the jekyll version still has some promising advantages in terms of simplifying dependencies, deployments and local search. This PR is nearly done, so I would suggest going with it. If with some experience it turns out really compelling to switch after all, we can revisit it later. It is nice to have that option though :]

**Comment by vsoch** [comment]
Definitely! If it comes down to it, switching just comes down to moving content around, and ensuring that links are ok. We can technically do it at any point, and I agree that we should give Hugo a chance. It's good to maximize the span of different technologies that one learns. :)

**Comment by Beanow** [comment]
Cool! I'll have a crack at using the updated image to build with and push that.

**Comment by Beanow** [comment]
I've made another wave of changes, this now builds on CI as well and uses the same docker image for building and a local previewing option. So you can avoid the dependency issues if you want.

Preview of a build running this on Drone: https://cloud.drone.io/Beanow/sfosc/11/1/2
Note it's red because this test build has no permissions for the github pages repository when it does the dry-run push.

Some noteworthy properties:
- Still uses the package-lock.json for postcss and autoprefix package version pinning (`npm install` in the deploy script). Even though the docker image includes postcss, it doesn't include the autoprefix plugin, so we'd need to install this anyway. But this has the added benefit of explicit version control and being able to upgrade independently from hugo. Hugo will prefer locally installed packages over global ones.
- The debian variety is used explicitly for builds (though this is an alias of the *-ext tag), because debian and ubuntu have ssh and ssh-keygen which we need for our git operations. In local previews you don't need this so alpine is suggested for that as it's about half the size.

**Comment by Beanow** [comment]
I do see one thing we could improve on: https://beanow.github.io/sfosc-pages/docs/ has some links in markdown like `[principles](/docs/principles/)` which are broken here because I have a baseURL of https://beanow.github.io/sfosc-pages/ and starting with `/` effectively strips the `/sfosc-pages` from it.

For `sfosc.org` it wouldn't be a problem, but we should look into fixing that.

**Comment by vsoch** [comment]
It's lovely!! <3

We will likely want to do some tweaks (mouse over colors, etc.) but I think this is a huge improvement over the current, and I also approve.

**Comment by Beanow** [comment]
Yes, I haven't reviewed on tweaks or an extensive proofreading level. Once we've got this technical overhaul out of the way, I think we can focus on content and tweaks a bit more.

**Comment by Beanow** [comment]
@adamhjk @karlamrhein @eliassecchi @camillem @nothingismagick @themightychris @nickkellett @marclaporte

Since this is a fairly extensive change are you able to help review this? And what you think of the new theme? Preview available here https://beanow.github.io/sfosc-pages/

**Comment by nothingismagick** [comment]
The only issue I found is that on some screens the navigation links at the top spill over.

Screen Shot 2019-08-07 at 18 32 05

Fix that and I'll approve it

**Comment by vsoch** [comment]
That's out of scope - it's an issue with the theme, and not anything that I did. It would need to be fixed upstream. You can look at https://example.docsy.dev/docs/, change the title to something long, and reproduce the same thing:

image

So, maybe you know a badass front end developer that could address this upstream, and then we can fix for here too :)

**Comment by vsoch** [comment]
Here's the same page (in a different color) to better reproduce

image

**Comment by Beanow** [comment]
That is, unless we could work around if the variable used to insert the title there can be changed to SFOSC and still make sense.

**Comment by vsoch** [comment]
I'd be okay with that, but we should make sure it's written out fully somewhere!

**Comment by vsoch** [comment]
That doesn't seem to overflow:

image

**Comment by nothingismagick** [comment]
YAY!

**Comment by nothingismagick** [comment]
Now just to get a logo competition running...

**Comment by vsoch** [comment]
Oh I love those - I want to be a judge!

**Comment by adamhjk** [comment]
This looks great! I love all of you.

**Comment by vsoch** [comment]
@adamhjk you're awesome!! I listened to you on the Changelog and then your talk on YouTube (from OSCON I think it's called - both about the war for the soul of open source?) and so much of what you said resonated with me. I didn't realize you wrote the sfosc book until I was working on this template and re-read your name, at which point I spit out my avocado and had a head :boom: moment. I found sfosc a few months back and have been so grateful to have a community to talk to about licenses, models, etc., and @Beanow and @nothingismagick have been really welcoming, and fun to work with. So yeah, keep doing what you do, and if you ever need a dinosaur developer, I can offer roars, random stomping around, and failed attempts at accomplishing tasks with my tiny arms.

**Comment by Beanow** [comment]
Setting the title to `SFOSC` there's still a couple of places where the full name can be found.

The homepage: http://localhost:1313/
Overview: http://localhost:1313/about/
Docs index: http://localhost:1313/docs/
Docs - About: http://localhost:1313/docs/about/

Perhaps some more, but I think we can use that as a fix for @nothingismagick's comment and merge this I believe :+1:

**Pull request merged**
