### PR TITLE
Add myself to the members

### PR DESCRIPTION
**Pull request by pradyunsg**
Colour me interested.

### CODE REVIEW

**Comment by pradyunsg** [comment]
WHoops. Too soon.

**Comment by nothingismagick** [comment]
Why too soon?

**Comment by nothingismagick** [comment]
I am asking about this because its not so clear to me why you would change your mind. It seems that your experience at PIP and the Maintainers group would fulfil the criteria of membership here:
```
You have either engaged with SFOSC directly, or have related experience we can verify.
If this experience is not easily found from your GitHub profile, please mention it as part 
of the pull request.
```

**Comment by Beanow** [comment]
Either way, glad to hear you're interested :]

Feel free to create/comment on issues for any subjects you'd like to dive into.
We're also on Discord, https://discord.gg/nz5NC9q
As well as short-handed, if you're willing to help perhaps you might share your insights on some of the many open discussions in the issues, or give us a heads up if there's any tasks you'd like to pick up.

**Comment by pradyunsg** [comment]
> Why too soon?

🙈

I accidentally filed the PR before I'd actually decided whether I have the time to budget to contribute significantly. :)

**Comment by nothingismagick** [comment]
In my opinion every contribution is significant and any time given is precious - but significance is something that you can only really measure when reflecting upon experience.  So my understanding of what you said is that you can't estimate the scope of commitment, and let me be the first to tell you that we prefer engagement to commitment. :)

**Pull request closed without merging**
