### PR TITLE
[WIP] Adding about pages

### PR DESCRIPTION
**Pull request by vsoch**
This PR is to start a discussion for #100. Specifically, all I've done is create a new folder subgroup that has a page to match each of the orphan markdown files in the root of the README. What we should discuss is what pages we want to keep in the main root of the repo, versus moving content here. There are three different scenarios:

 1. Keep a page entirely in the repository root, no mention in about
 2. Remove a page from the repository root, maintain in about
 3. Keep the page in the repository root, but summarize (and link) from about
 4. Create a main page in about, and then link from repository root.

I think for most points we would want to do 3 or 4? However I don't have strong opinion, and for this reason I just created a basic template that we could work with / discuss. The pages in question are:

## Membership
Perhaps the cruft of description should be in about, and then just have the actual list of people and a link to the about document in the repository root?

## Code of Conduct
This one I think belongs in the root. I did a little summary page, because someone might go looking for it in about (and they should find it).

## Contributing
This one is probably akin to the code of conduct, and should remain is it's strongest form in the root of the repository. We could summarize here and link to that (although I didn't do it).

 - voting
 - trademark

These are tiny awkward files in the root of the repository, and unless they are standard / known files (akin to CONTRIBUTING.md) I think they might do better to be in the about docs.

## Social Contract

This also seems like it's better in about, of course unless it's a known thing.

Hopefully this will get us started, tear it up! I've also checked to allow edits from maintainers (actually I usually do :P) and I'll invite you to hack it up to your liking (vs. giving me play by play changes).

 
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by Beanow** [comment]
Ooo, very nice. And share the concern about maintaining it in two places now.
Maybe there's a good way to convince hugo to copy the content from the repository root and add on the metadata?

**Comment by vsoch** [comment]
Well, if we create a symbolic link that will come down to GitHub simply maintaining both files (I think?). If that would work, we would still need to add the front end matter to the files (or whatever hugo calls the header section). It could be that hugo can include snippets (includes in jekyll) but I would guess it's not allowed to be outside of some root (if it's the root of the repo, maybe it would work!) Anyway - I fork this forward to someone that knows more about hugo. I'll definitely do some digging later today to see if I can figure something out (because that would be a nice solution!)

**Comment by vsoch** [comment]
Maybe these things called shortcodes? https://discourse.gohugo.io/t/is-it-possible-to-embed-partials-in-markdown/9335/3

**Comment by Beanow** [comment]
Ooh, yes that looks like what we need https://gohugo.io/functions/readfile/

**Comment by vsoch** [comment]
Just figured it out!

I want to mess around with some other things (mostly just learning) but I'll update the PR after that.

**Comment by vsoch** [comment]
okay going to take some screenshots to show what I'm working on. The readfile works beautifully, and I did it by adding something called a shortcode, and then in the content we use the shortcode with a file and markdown set to true.

However, reading in any of these pages, it looks pretty terrible because there is a double title:

image

So what I did is add an extra optional variable to the header to hide the title (and here I'll also show the shortcode)

```
+++
title = "Membership"
date = 2018-12-06T12:27:40-08:00
weight = 5
hideTitle = "true"
+++

{{< readfile file="MEMBERSHIP.md" markdown="true" >}}
```

and it looks so much better! 

image

The shortcode file being used (readfile.html) is the one in the example:

```
{{$file := .Get "file"}}
{{- if eq (.Get "markdown") "true" -}}
{{- $file  | readFile | markdownify -}}
{{- else -}}
{{ $file  | readFile | safeHTML }}
{{- end -}}
```

Here is the update to the theme (the div shown for context on the page)

```
        <div id="body-inner">
          {{if and (not .IsHome) (not .Params.chapter) }}
            {{if not .Params.hideTitle }}
              <h1>{{.Title}}</h1>
            {{end}}
          {{end}}
```
I'm still fussing around :) Will update the PR in a bit!

**Comment by vsoch** [comment]
okay just pushed an update! Hugo is awesome!

**Comment by Beanow** [comment]
Awesome! I ran a few tests with it and have just technical nitpicking to add.

Booleans are supported, so `hideTitle = "false"` is a string and would evaluate as true-ish.
I found this out, because I tend to choose positive variable names. In this case `renderTitle` vs `hideTitle`.

I've added them both in a commit, with this change an explicit false is required. True-ish or unset will render the title.

**Comment by vsoch** [comment]
Wait, so now what about all the other pages that don't have renderTitle defined at all? The reason I chose one that would be present / true is because we don't want to need to add an unnecessary variable to every page, just a boolean to the few we want to hide.

**Comment by vsoch** [comment]
Ah I see, it's set:

```
{{if .Params.renderTitle | or (not (isset .Params "rendertitle")) }}
              <h1>{{.Title}}</h1>
            {{end}}
```
This wouldn't have been my choice, but if it's your preference I'm okay with it. I think the original having one variable akin to `--no-cache` `--dont-do-this-thing` would have been okay.

**Comment by Beanow** [comment]
Yes, using isset I'm basically adding a default value of true for renderTitle.

It's not a strong preference here. It goes into grey areas quickly with stuff like `isPreview` from #98.
What's positive? Should it be `isProduction = false`? etc. etc.

So long as the booleans are not strings I'd approve either variable name.

**Comment by vsoch** [comment]
I think we should do the original then - a future developer looking at the variable won't obviously know that it's also checked to be set, and would have to test to confirm, or just blindly add to new pages (that don't need it).

**Comment by nothingismagick** [comment]
I don't care about HOW this is implemented, I just approve.

**Comment by vsoch** [comment]
@Beanow okay if I change it back?

**Comment by Beanow** [comment]
> I think we should do the original then - a future developer looking at the variable won't obviously know that it's also checked to be set, and would have to test to confirm, or just blindly add to new pages (that don't need it).

That's fair.

> @Beanow okay if I change it back?

Yes :]

**Comment by vsoch** [comment]
okay, all set :)

**Comment by Beanow** [comment]
LGTM, leaving this on cooldown for a little bit considering #71 ~2 day review window

**Comment by Beanow** [comment]
With no further comments/reviews I'll merge this in now.

**Pull request merged**
