### PR TITLE
Applying for membership

### PR DESCRIPTION
**Pull request by Beanow**
As [pointed out](https://github.com/sfosc/sfosc/pull/54#issuecomment-491424989) I had not applied for membership yet.

Since I have received maintainer access as well in #60 I'll share a more detailed introduction while I start chipping away at some of the backlog.

### CODE REVIEW

**Comment by Beanow** [comment]
Especially since this is my own application, I think it's best to follow #71 in requiring at least one more approval.

**Comment by nothingismagick** [comment]
Thinking more about this, I believe that the fact that @adamhjk approved you as a maintainer is an inherent approval for community membership.

**Comment by nothingismagick** [comment]
But you'll need to fix the conflict. ;)

**Comment by Beanow** [comment]
> Thinking more about this, I believe that the fact that @adamhjk approved you as a maintainer is an inherent approval for community membership.

Makes sense to me, I'll roll with that and merge then :smile:

**Pull request merged**
