### PR TITLE
Fix info on MySQL business model: it is primarily support

### PR DESCRIPTION
**Pull request by federico-razzoli**
Fixes issue #35

### CODE REVIEW

**Comment by Beanow** [comment]
Thank you, and LGTM :+1:

**Comment by Beanow** [comment]
This PR is stalled on a second review anyone able to have a look at this and #35 for context?

**Comment by nothingismagick** [comment]
So while reviewing the PR, I noticed the timestamps of the two files still show December. Shouldn't those be changed as well?

**Comment by Beanow** [comment]
From what I can tell the date isn't used in the hugo templates. Probably more relevant for blog/article themes. Should we need last modified dates it seems there's ways to use git for this: https://gohugo.io/variables/git/#lastmod

**Comment by nothingismagick** [comment]
OK, I just wanted to bring it up.

**Pull request merged**
